scene_opt = {
    "n_rays": [8192],
    "image_batch_size": [
        2,
    ],
    "chunk": [64000],
    "scenes": ["wiindoor"],
    "precache": [False],
    "latent_balance": 0.0001,
    "lrate_decay": 250,
    "netchunk": 65536,
    "lightfield": {
        "k_closest": 8,
        "n_features": 128,
        "n_sample_pts": 500,
        "merge_pcd": True,
        "all_cams": False,
        "D_lf": 8,
        "W_lf": 256,
        "skips_lf": [4],
        "layer_modulation": False,
        "camera_centered": False,
        "augment_frame_order": True,
        "new_enc": False,
        "torch_sampler": True,
        "sky_dome": True,
        "num_merged_frames": 20,
        "ray_encoding": 2,
    },
    "scale": 0.125,
    "version": 0,
    "point_chunk": 1e7,
    "tonemapping": False,
    "pose_refinement": False,
    "pt_cache": True,
}
